### ISSUE TITLE
Roadmap of Missing Core Features

### ISSUE THREAD

**Issue by timbitz** [timbitz/Whippet.jl#1]
- [x] Paired-End Reads Support --> `paired_ungapped_align` to `align.jl`
- [x] Alt-First/Last and tandem-UTR support
- [x] Confidence Intervals & better output
- [x] BAM output flag
- [x] Circular splicing output
- [x] Basic usage documentation
