### ISSUE TITLE
Julia 1.0 migration

### ISSUE THREAD

**Issue by datakid** [timbitz/Whippet.jl#73]
Julia 0.6.4 is now in [old releases](https://julialang.org/downloads/oldreleases.html) and isn't generally available.

Any chance this could be addressed?

**Comment by timbitz** [comment]
This should be possible now. The roadmap to Whippet v1.0 looks something like this:
- [x] Update WaveletMatrices.jl to Julia 1.0 (https://github.com/BioJulia/WaveletMatrices.jl/pull/5)
- [x] Update SuffixArrays.jl to Julia 1.0 (https://github.com/quinnj/SuffixArrays.jl/pull/9)
- [ ] Update FMIndexes.jl to Julia 1.0 (in progress - I still need to make this PR)
- [ ] Whippet.jl syntax updates for Julia 1.0 (in progress - branch 0.7-update)
- [ ] Whippet.jl migration from Requests.jl to HTTP.jl
- [ ] Whippet.jl bugfix #79 
- [ ] Whippet.jl feature addition #78 
- [ ] Whippet.jl feature addition #74
